- name: Add the repository for MySql 5.6
  become: yes
  command: sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'

- name: Update
  become: yes
  command: sudo apt-get update

- name: Install mysql-server-5.6
  apt: 
    name:   
      - mysql-server
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  
- name: Install mysql-client-5.6
  apt: 
    name:   
      - mysql-client
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
- name: Install python-mysqldb
  apt: 
    name:   
      - python-mysqldb
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
- name: Install libmysqlclient-dev
  apt: 
    name:
      - libmysqlclient-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }}
              login_user=root
              login_password={{ mysql_root_password }}
              state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
