- name: Add the repository for MySql 5.6
  become: yes
  command: sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'

- name: Update
  become: yes
  command: sudo apt-get update

- name: Install mysql
  apt: 
    name:   
      - mysql-server-5.6
      - mysql-client-5.6
      - python-mysqldb
      - libmysqlclient-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  mysql_user: name=root 
              host= 127.0.0.1 
              password={{ mysql_root_password }}
              login_user=root
              login_password=""
              state=present
